<a href="https://colab.research.google.com/github/bernlkb/STQD6014-DataScience/blob/main/02_Week10_DataWrangling_20241215.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 10: Data Wrangling: Clean, Transform, Merge, Reshape**
For details of this Topic (Data Wrangling: Clean, Transform, Merge, Reshape), please refer to the textbook: "Python for Data Analysis" by Wes McKinney

**Chapter 7 & 8**

### **Always starts by importing Pandas and NumPy library - it's like a template :)**

In [1]:
# Load library
import pandas as pd
import numpy as np

## **Filling In Missing Data**

In [6]:
# Create a mock data
# Set a seed for reproducibility
np.random.seed(1312)
df = pd.DataFrame(np.random.standard_normal((7,3)))
df

0         1         2
0  0.849933 -0.142354  1.658247
1  0.096458 -0.463639 -0.621719
2 -0.157222  0.106894 -0.970226
3  0.411543 -0.493338 -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

### **iloc -> integer-location based indexing**

In [7]:
# Randomly add in the missing data
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [8]:
# Filling the NaN with a constant
# Sentinel data -> placeholders
# changes happens only by display
df_edit = df.fillna(-999)
df_edit

0           1           2
0  0.849933 -999.000000 -999.000000
1  0.096458 -999.000000 -999.000000
2 -0.157222 -999.000000   -0.970226
3  0.411543 -999.000000   -0.374906
4  0.144656    1.082482    0.975774
5 -0.759141    0.701347   -0.538854
6 -0.496170   -0.490029   -1.265389

In [9]:
# Display the df output
# Notice that df is still intact
# Function fillna() does not modify the DataFrame by default
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [10]:
# Calling fillna with a different fill value for each column
# changes by display only
df.fillna({1: 0.67, 2: -1.11})

0         1         2
0  0.849933  0.670000 -1.110000
1  0.096458  0.670000 -1.110000
2 -0.157222  0.670000 -0.970226
3  0.411543  0.670000 -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [11]:
# Display df output
# Not affecting the df
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [12]:
# Challenge: Change cell at (2,0) to 0.37
# This will change the data frame permanently
df.iloc[2,0] = 0.37
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2  0.370000       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [13]:
# Display df output
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2  0.370000       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [14]:
# Challenge
# Another dummy data 2
np.random.seed(1234)
df = pd.DataFrame(np.random.standard_normal((6,3)))
df

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.636524  0.015696
3 -2.242685  1.150036  0.991946
4  0.953324 -2.021255 -0.334077
5  0.002118  0.405453  0.289092

In [15]:
# iloc - integer index
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588       NaN  0.015696
3 -2.242685       NaN  0.991946
4  0.953324       NaN       NaN
5  0.002118       NaN       NaN

In [16]:
# 'ffill' -> forward fill
# uses the previous valid (non-missing) value to replace the NaN
df.ffill()

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324 -0.720589  0.991946
5  0.002118 -0.720589  0.991946

In [18]:
# fill na limit to 2
df.ffill(limit=2)

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324       NaN  0.991946
5  0.002118       NaN  0.991946

In [19]:
# Another example 3
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [20]:
# Data imputation using median
data.fillna(data.median())

0    1.0
1    3.5
2    3.5
3    3.5
4    7.0
dtype: float64

# **Data Transformation**
Filtering, cleaning, and other transformations

### **Removing Duplicates**

In [21]:
# Example data with duplicate rows
data = pd.DataFrame({"k1": ['one', 'two'] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4,]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

# The ***duplicated() function*** returns a ***Boolean Series*** indicating whether each row is a duplicate to those in an ***earlier row***

In [22]:
data.duplicated?

In [23]:
# Detect duplication of data row-wise
# data.duplicated?
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
# Returns a DataFrame with rows where the duplicated array is filtered out
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
# Add dummy data
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [26]:
# Filter duplicates based only on the "k1" column
# By default, keep the first observed value combination
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [27]:
# Passing keep="last" will return the last one
# Remove index 5
print(data)
print('\n--------------\n')
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

--------------



k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### **Transforming Data Using Mapping**

In [28]:
# Mock data
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'pastrami', 'corned beef', 'bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [29]:
# Mapping of each distinct animal type
# This is a library of food to animal
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}


In [30]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [31]:
# Mapping method
data['animal'] = data['food'].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### **Replacing Values**

In [32]:
# Mock data
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [33]:
# Set -999 values as sentinel value for missing data
# sentinel value -> unique value indicating certain meaning
# Special value that is used to signal the end of a sequence, indicate an error,
# or serve as a termination condition in a program.
data.replace(-999, 'No data available')

0                  1.0
1    No data available
2                  2.0
3    No data available
4              -1000.0
5                  3.0
dtype: object

In [35]:
# Replace multiple sentinel values at once
data.replace([-999, -1000], 'No data available')

0                  1.0
1    No data available
2                  2.0
3    No data available
4    No data available
5                  3.0
dtype: object

In [36]:
# Use a different replacement for each sentinel value
data.replace([-999, -1000], ['No data available', 'Tiada maklumat'])

0                  1.0
1    No data available
2                  2.0
3    No data available
4       Tiada maklumat
5                  3.0
dtype: object

In [37]:
# Argument passed as a dictionary
data.replace({-999: 'No data avaialble', -1000: 'no no no'})

0                  1.0
1    No data avaialble
2                  2.0
3    No data avaialble
4             no no no
5                  3.0
dtype: object

### **Renaming Axis Indexes**

In [38]:
# Mock example
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index = ['ohio', 'ukm', 'bangi'],
                    columns = ['one', 'two', 'tiga', 'empat'])
data

one  two  tiga  empat
ohio     0    1     2      3
ukm      4    5     6      7
bangi    8    9    10     11

In [39]:
# Add another column
data['five'] = np.random.standard_normal(3)
data

one  two  tiga  empat      five
ohio     0    1     2      3  1.321158
ukm      4    5     6      7 -1.546906
bangi    8    9    10     11 -0.202646

In [40]:
# Define a transform() function
def transform(x):
    return x[:].upper()

data.index.map(transform)

Index(['OHIO', 'UKM', 'BANGI'], dtype='object')

In [41]:
# Rename indexes
# To uppercase
data.index = data.index.map(transform)
data

one  two  tiga  empat      five
OHIO     0    1     2      3  1.321158
UKM      4    5     6      7 -1.546906
BANGI    8    9    10     11 -0.202646

# Create a transformed version of a dataset ***without modifying the original***, a useful method is ***rename***

In [42]:
# Display data
data

one  two  tiga  empat      five
OHIO     0    1     2      3  1.321158
UKM      4    5     6      7 -1.546906
BANGI    8    9    10     11 -0.202646

In [43]:
# rename() function
# columns -> column names
data.rename(index=str.title, columns=str.upper)

ONE  TWO  TIGA  EMPAT      FIVE
Ohio     0    1     2      3  1.321158
Ukm      4    5     6      7 -1.546906
Bangi    8    9    10     11 -0.202646

In [45]:
# Rename can be used in conjunction with a dictionary-like object
data.rename(index = {'OHIO': 'New York', 'New': 'Old'},
            columns = {'tiga': 'peekaboo', 'five': 'Seven'})

one  two  peekaboo  empat     Seven
New York    0    1         2      3  1.321158
UKM         4    5         6      7 -1.546906
BANGI       8    9        10     11 -0.202646

In [46]:
# The original data remains intact
print(data)

       one  two  tiga  empat      five
OHIO     0    1     2      3  1.321158
UKM      4    5     6      7 -1.546906
BANGI    8    9    10     11 -0.202646


### **Discretization and Binning**
- used to <font color='red'>**transform continuous data**</font> into <font color='red'>**discrete categories**</font> or <font color='red'>**intervals (bins)**</font>

In [47]:
# Mock data
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [50]:
# Divide into bins of 18 to 25, 26 to 35, 36 to 60, and finally 61 and older
# returns a Categorical object
# "(" -> Open parenthesis: Indicates that the value is not included in the interval
# "]" -> Closed square bracket: Indicates that the value is included in the interval
# (18, 25] -> interval includes values greater than 18 and less than or equal to 25.
bins = [18, 25, 35, 100]
age_cut = pd.cut(ages, bins)
age_cut

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 100], (35, 100], (35, 100], (25, 35]]
Length: 12
Categories (3, interval[int64, right]): [(18, 25] < (25, 35] < (35, 100]]

### **Unique pandas categorical object**

In [49]:
# Codes
age_cut.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1], dtype=int8)

In [51]:
# Categories
age_cut.categories

IntervalIndex([(18, 25], (25, 35], (35, 100]], dtype='interval[int64, right]')

In [52]:
# Accessing single elements
# closed -> inclusive
age_cut.categories[2]

Interval(35, 100, closed='right')

In [53]:
# Count number of each category
pd.Series(age_cut).value_counts()

(18, 25]     5
(35, 100]    4
(25, 35]     3
Name: count, dtype: int64

In [54]:
age_cut.value_counts()

(18, 25]     5
(25, 35]     3
(35, 100]    4
Name: count, dtype: int64

• **parenthesis ( )** means that the side is open (**exclusive**)

• **square [ ]** bracket means it is closed [**inclusive**]

• Example: **[first1, last1)** , the range starts with first1 (and includes it), but ends just before last1

In [55]:
# Inclusive of left, exclusive (not include) right
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [35, 100), [35, 100), [35, 100), [25, 35)]
Length: 12
Categories (3, interval[int64, left]): [[18, 25) < [25, 35) < [35, 100)]

In [56]:
# Exclusive of left, inclusive of right
pd.cut(ages, bins, right=True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 100], (35, 100], (35, 100], (25, 35]]
Length: 12
Categories (3, interval[int64, right]): [(18, 25] < (25, 35] < (35, 100]]

In [57]:
# Override the default interval-based bin labeling by passing a list or
# array to the labels option
gp_names = ["Youth", "MiddleAge", "Senior"]
pd.cut(ages, bins, labels=gp_names)

['Youth', 'Youth', 'Youth', 'MiddleAge', 'Youth', ..., 'MiddleAge', 'Senior', 'Senior', 'Senior', 'MiddleAge']
Length: 12
Categories (3, object): ['Youth' < 'MiddleAge' < 'Senior']

In [58]:
# Some mock data
data = np.random.uniform(size=20)
data

array([0.9331401 , 0.65137814, 0.39720258, 0.78873014, 0.31683612,
       0.56809865, 0.86912739, 0.43617342, 0.80214764, 0.14376682,
       0.70426097, 0.70458131, 0.21879211, 0.92486763, 0.44214076,
       0.90931596, 0.05980922, 0.18428708, 0.04735528, 0.67488094])

In [59]:
# Pass an integer number of bins to pandas.cut to compute equal-length bins
# Based on the minimum and maximum values in the data
# Compute equal-length bins
# four quadrants -> each is 25%
# Precision=2 option limits the decimal precision to two digits
pd.cut(data, 4, precision=2)

[(0.71, 0.93], (0.49, 0.71], (0.27, 0.49], (0.71, 0.93], (0.27, 0.49], ..., (0.71, 0.93], (0.046, 0.27], (0.046, 0.27], (0.046, 0.27], (0.49, 0.71]]
Length: 20
Categories (4, interval[float64, right]): [(0.046, 0.27] < (0.27, 0.49] < (0.49, 0.71] <
                                           (0.71, 0.93]]

In [60]:
# Pandas.qcut bins the data based on sample quantiles
# Set the random seed
np.random.seed(5108)
data = np.random.standard_normal(size=1000)
quartiles = pd.qcut(data, 4, precision = 2)
quartiles

[(-0.0011, 0.66], (-3.0599999999999996, -0.68], (-3.0599999999999996, -0.68], (0.66, 3.04], (-0.68, -0.0011], ..., (-0.68, -0.0011], (-0.0011, 0.66], (-3.0599999999999996, -0.68], (-0.0011, 0.66], (-0.68, -0.0011]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0599999999999996, -0.68] < (-0.68, -0.0011] < (-0.0011, 0.66] <
                                           (0.66, 3.04]]

In [61]:
# Count each catagory
quartiles.value_counts()

(-3.0599999999999996, -0.68]    250
(-0.68, -0.0011]                250
(-0.0011, 0.66]                 250
(0.66, 3.04]                    250
Name: count, dtype: int64

In [62]:
# Another example
# Based on user-defined quartiles
pd.cut(data, [0, 0.1, 0.5, 0.9,1.]).value_counts()

(0.0, 0.1]     37
(0.1, 0.5]    164
(0.5, 0.9]    110
(0.9, 1.0]     31
Name: count, dtype: int64

### **Detecting and Filtering Outliers**

In [ ]:
# DataFrame with some normally distributed data
# DataFrame of 1000x4


0         1         2         3
0   -1.659900  0.208843  0.598739 -0.596664
1    0.839935 -1.839990  0.964221 -2.257445
2   -0.784775 -2.027094 -0.993469  0.559212
3   -0.117450  0.410928  0.318748  0.639331
4   -0.521970 -0.311916  0.521761  0.210571
..        ...       ...       ...       ...
995 -0.327149 -0.488389 -1.135903  0.189588
996 -1.507982 -0.088997 -0.878277  0.264910
997 -0.594736 -0.701838  0.354915  0.269142
998 -1.649264  1.000086  2.774826 -0.665264
999  0.013210  0.643625  0.768772  0.243135

[1000 rows x 4 columns]

In [ ]:
# Explore the dataset in terms of statistics


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.013366    -0.013265     0.070596    -0.013219
std       0.973572     1.021529     1.004823     0.972546
min      -2.749576    -2.947203    -3.193919    -3.247803
25%      -0.669586    -0.731677    -0.577050    -0.644001
50%      -0.013198    -0.045057     0.051107    -0.009525
75%       0.682270     0.686080     0.746779     0.599635
max       3.262460     3.112566     3.281679     3.181885

In [ ]:
# Find values in one of the columns exceeding 3 in absolute value
# Extracting 3rd column


16    -3.193919
63    -3.173719
313    3.281679
928    3.003493
964    3.129080
Name: 2, dtype: float64

In [ ]:
# Select any rows having at least one value exceeding sd of 3 or –3


0         1         2         3
15   1.227008  3.112566 -0.854092  1.260485
16  -1.155939 -2.050703 -3.193919  1.386524
63  -1.347788 -0.310825 -3.173719 -0.966218
97   1.502350 -0.882800  0.345232  3.181885
313  0.673852  0.442783  3.281679 -0.516406
559  2.228441  3.024606 -1.978088  0.398960
591  0.054571  1.078003 -1.274146 -3.247803
727  3.262460 -0.577847  0.443450 -1.232069
871  3.176068 -1.003907  1.191888  0.034887
928  0.974109 -0.766643  3.003493 -0.862603
964 -1.026628 -0.718284  3.129080 -0.309517

In [ ]:
# Cap values outside the interval, more than abs(sd) = 3 to minimum –3 and maximum 3


0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.013805    -0.013402     0.070549    -0.013153
std       0.972161     1.021118     1.002405     0.971170
min      -2.749576    -2.947203    -3.000000    -3.000000
25%      -0.669586    -0.731677    -0.577050    -0.644001
50%      -0.013198    -0.045057     0.051107    -0.009525
75%       0.682270     0.686080     0.746779     0.599635
max       3.000000     3.000000     3.000000     3.000000

### **Permutation and Random Sampling**
- Permutation - process of rearranging the order of elements within a dataset
- This rearrangement is often **done randomly**, meaning that the elements are shuffled into a **new, unpredictable order**.

In [ ]:
# 2d array of 5x7


0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [ ]:
# Random sampling


array([0, 1, 3, 2, 4])

In [ ]:
# sampling of the array


0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [ ]:
# Another way


0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34

In [ ]:
# Select a permutation of the columns


array([6, 0, 3, 5, 2, 1, 4])

In [ ]:
# Sample the colummns
print(df)
print('\n--------\n')


    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

--------



6   0   3   5   2   1   4
0   6   0   3   5   2   1   4
1  13   7  10  12   9   8  11
2  20  14  17  19  16  15  18
3  27  21  24  26  23  22  25
4  34  28  31  33  30  29  32

In [ ]:
# Select a random subset without replacement


0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [ ]:
# Example dataset


0    5
1    7
2   -1
3    6
4    4
dtype: int64

### <font color='red'>**`replace=False`**</font>
- indicates that we are performing sampling without replacement

In [ ]:
# Generate a sample with replacement


2   -1
1    7
3    6
4    4
0    5
dtype: int64

### **Computing Indicator/Dummy Variables**
Converting a categorical variable into a dummy or indicator matrix

In [ ]:
# Example dataframe
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Get dummy dataFrame based on the key


a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
# Add a prefix


key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [ ]:
# Example data from previous
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Merging of dataset based on the same index number
print(df)
print('\n--------\n')
print(dummies)
print('\n--------\n')


  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

--------

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

--------



data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [ ]:
# DataFrame with multiple categories
# movies.dat -> Data can be downlaoded here: https://bit.ly/3VA5elU


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller

In [ ]:
# Get data from the genres column


Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1

### **String Manipulation**

In [ ]:
# A comma-separated string can be broken into pieces with split
val = "a,b,  guido"


['a', 'b', '  guido']

In [ ]:
# Split is often combined with strip to trim whitespace


['a', 'b', 'guido']

In [ ]:
# Substrings could be concatenated together with a
# Two-colon delimiter using addition


'a::b::guido'

In [ ]:
# Another way


'a::b::guido'

In [ ]:
# Return starting index of the first occurrence of passed substring
# If found in the string


10

In [ ]:
# Count returns the number of occurrences


2

### **Regular Expressions**
***regex*** describes a ***pattern to locate*** in the text, which can then be used for many purposes

### <font color='red'>**`r"\s+"`**</font>
- <font color='red'>**`r""`**</font>: This designates a **raw string literal**, which is often used for regular expressions to avoid escaping issues with **backslashes (`\`)**.
- <font color='red'>**`\s+`**</font>: This is the actual regular expression pattern. It **matches one or more whitespace characters**.

In [ ]:
# Regex describing one or more whitespace characters -> \s+
# raw string (r"\s+") is often preferred in regular expressions to enhance readability and avoid potential issues with escaping
import re


foo bar	 baz 	qux

----



['foo', 'bar', 'baz', 'qux']

In [ ]:
# Compile the regex with re.compile, forming a reusable regex object
# r'\s+' refers to sequence of whitespace
# Avoid unwanted escaping with \ in a regular expression


['foo', 'bar', 'baz', 'qux']

In [ ]:
# A block of text example
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

# Display text
print(text)

# The pattern to search
# Match a typical email address pattern
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive


Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com


In [ ]:
# Extract the information based on the pattern


['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

### **String Functions in pandas**
Cleaning up a messy dataset for analysis often requires a lot of string manipulation

In [ ]:
# A column containing strings with missing data
# in dictionary form
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
# Check missing data


Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
# Series has array-oriented methods for string operations that skip over
# and propagate NA values


Dave      True
Steve    False
Rob      False
Wes        NaN
dtype: object

In [ ]:
# String data type


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [ ]:
# Boolean data type


Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

### **Categorical Data**

In [ ]:
# A mock data


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [ ]:
# Extract distinct values


array(['apple', 'orange'], dtype=object)

In [ ]:
# Count


apple     6
orange    2
Name: count, dtype: int64

### **Categorical Extension Type in pandas**
integer-based categorical representation or ***encoding***

In [ ]:
# Some example Series
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [ ]:
# Convert df['fruit'] into categorical; original is a string


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
# Accessing the array attribute


pandas.core.arrays.categorical.Categorical

In [ ]:
# Category


Index(['apple', 'orange'], dtype='object')

In [ ]:
# codes


array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

### <font color='red'>**`enumerate()`**</font>
- is used to **create a dictionary** that **maps the index positions of the categories** to their **corresponding values**

In [ ]:
# Mapping between codes and categories
# Returns pairs of index and value.


{0: 'apple', 1: 'orange'}

### **Computations with Categoricals**

In [ ]:
# Some mock data
rng = np.random.default_rng(seed=12345)



array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [ ]:
# Compute a quartile binning


[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [ ]:
# Using labels argument


['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [ ]:
# Accessing codes


array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [ ]:
# Use groupby to extract summary statistics


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

### **Categorical Methods**

In [ ]:
# Some mock data
s = pd.Series(['a', 'b', 'c', 'd'] * 2)


0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
# cat provides access to categorical methods -> the codes
# returns the integer codes associated with each category in the categorical series


0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [ ]:
# Accessing the categories data


Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# set_categories method to change new category
actual_categories = ['a', 'b', 'c', 'd', 'e']


0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [ ]:
# value_counts for cat_s


a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [ ]:
# value_counts for cat_s2


a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

### **Hierarchical Indexing**

In [ ]:
# An example
data = pd.Series(np.random.uniform(size=9),
                 index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1,2,3,1,3,1,2,2,3]])
data

a  1    0.226575
   2    0.959381
   3    0.818023
b  1    0.353897
   3    0.183883
c  1    0.295739
   2    0.203237
d  2    0.257583
   3    0.374762
dtype: float64

In [ ]:
# Access the index


MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
# Partial indexing


1    0.353897
3    0.183883
dtype: float64

In [ ]:
# Partial indexing


b  1    0.353897
   3    0.183883
c  1    0.295739
   2    0.203237
dtype: float64

In [ ]:
# Partial indexing
# loc[] -> label-based indexing


b  1    0.353897
   3    0.183883
d  2    0.257583
   3    0.374762
dtype: float64

In [ ]:
# Partial indexing
print(data)
print('\n---------\n')


a  1    0.226575
   2    0.959381
   3    0.818023
b  1    0.353897
   3    0.183883
c  1    0.295739
   2    0.203237
d  2    0.257583
   3    0.374762
dtype: float64

---------



a    0.959381
c    0.203237
d    0.257583
dtype: float64

In [ ]:
# Rearrange this data into a DataFrame using its unstack method


1         2         3
a  0.226575  0.959381  0.818023
b  0.353897       NaN  0.183883
c  0.295739  0.203237       NaN
d       NaN  0.257583  0.374762

In [ ]:
# Reverse the operation of unstack -> stack


a  1    0.226575
   2    0.959381
   3    0.818023
b  1    0.353897
   3    0.183883
c  1    0.295739
   2    0.203237
d  2    0.257583
   3    0.374762
dtype: float64

In [ ]:
# Another example
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                     columns=[["Ohio", "Ohio", "Colorado"],
                              ["Green", "Red", "Green"]])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
# add key names


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [ ]:
# Partial indexing


color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### **Reordering and Sorting Levels**

In [ ]:
# Rearrange key


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [ ]:
# Another example of rearrange
# level=1 -> the sorting is based on the values in the second level of the index.
print(frame)
print('\n-------\n')


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

-------



state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

### **Summary Statistics by Level**

In [ ]:
# Sum


state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [ ]:
# Another example


<ipython-input-211-a817f962dedf>:2: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color", axis="columns").sum()


color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

### **Indexing with a DataFrame’s columns**

In [ ]:
# Example dataframe
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                      "c": ["one", "one", "one", "two", "two",
                            "two", "two"],
                      "d":[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [ ]:
# Create a new DataFrame using one or more of its columns as the index


a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [ ]:
# Leave the column intact


a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [ ]:
# Move the index back to columns


c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

### **Combining and Merging Datasets**

### **Database-Style DataFrame Joins**

In [ ]:
# Example datasets
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
# By default - inner join
# keeps only the rows where the "key" values exist in both DataFrames
# Using the same common "feature"


key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [ ]:
# Different column names
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [ ]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [ ]:
# Merge - inner join by default - intersection
# Using specific key


rkey  data2 lkey  data1
0    a      0    a      2
1    a      0    a      4
2    a      0    a      5
3    b      1    b      0
4    b      1    b      1
5    b      1    b      6

In [ ]:
# Merge - outer join - union
print(df1)
print('\n----\n')
print(df2)
print('\n----\n')


  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

----

  key  data2
0   a      0
1   b      1
2   d      2

----



key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [ ]:
# Merge - outer join - union
print(df3)
print('\n----\n')
print(df4)
print('\n----\n')


  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

----

  rkey  data2
0    a      0
1    b      1
2    d      2

----



lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

### **Many-to-many merges**

In [ ]:
# A mock data
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})

In [ ]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [ ]:
# left-join


key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [ ]:
# inner join
# Intersection


key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [ ]:
# merge with multiple keys
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})


In [ ]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [ ]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [ ]:
# Outer join


key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

### **Concatenating Along an Axis**
***axis=0***; ***moves down*** the column

***axis=1***; ***moves across*** the column to the right

In [ ]:
# an example


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Along the column


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

### **Reshaping**
reshape or pivoting - rearranging tabular data

### **Pivoting**
- a specific type of **data reshaping** operation where we:

    - **Transform data from a "long" format to a "wide" format (or vice-versa)**.
    - **Use one or more columns as new column headers**.
    - **Aggregate values in other columns to populate the new structure.**

### ***Reshaping with Hierarchical Indexing***

In [ ]:
# Example data
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                                     name="number"))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Using the stack method to pivot the columns into the rows


state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [ ]:
# Rearrange


number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Unstack a different level by passing a level number or name


state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
# Using name


state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

### **`Int64`**
- Pandas data type that can handle **nullable integers**.
- **Nullable** means it can **store regular integer values** as well as **missing values** (represented as pd.NA).

In [ ]:
# Example
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")
s1

a    0
b    1
c    2
d    3
dtype: Int64

In [ ]:
# example 2
s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")
s2

c    4
d    5
e    6
dtype: Int64

In [ ]:
# Concatenate


one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [ ]:
# Unstacking


a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [ ]:
# Return original state


one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

# **All the best and good luck!!!**









