<a href="https://colab.research.google.com/github/bernlkb/STQD6014-DataScience/blob/main/Week10_DataWrangling_20231213_WC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Week 10: Data Wrangling: Clean, Transform, Merge, Reshape**
For details of this Topic (Data Wrangling: Clean, Transform, Merge, Reshape), please refer to the textbook: "Python for Data Analysis" by Wes McKinney

**Chapter 7 & 8**

### **Always starts by importing Pandas and NumPy library - it's like a template :)**

In [1]:
# Load library
import pandas as pd
import numpy as np

## **Filling In Missing Data**

In [2]:
# Create a mock data
# Set a seed for reproducibility
np.random.seed(1312)
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0  0.849933 -0.142354  1.658247
1  0.096458 -0.463639 -0.621719
2 -0.157222  0.106894 -0.970226
3  0.411543 -0.493338 -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [4]:
# Randomly add in the missing data
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [8]:
# Filling the NaN with a constant
# Sentinel data
# changes happens only by display
df_edit = df.fillna(-999)
df_edit

0           1           2
0  0.849933 -999.000000 -999.000000
1  0.096458 -999.000000 -999.000000
2 -0.157222 -999.000000   -0.970226
3  0.411543 -999.000000   -0.374906
4  0.144656    1.082482    0.975774
5 -0.759141    0.701347   -0.538854
6 -0.496170   -0.490029   -1.265389

In [9]:
# Display the df output
# Notice that df is still intact
# Function fillna() does not modify the DataFrame by default
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [10]:
# Calling fillna with a different fill value for each column
# changes by display only
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.849933  0.500000  0.000000
1  0.096458  0.500000  0.000000
2 -0.157222  0.500000 -0.970226
3  0.411543  0.500000 -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [11]:
# Display df output
# Not affecting the df
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2 -0.157222       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [13]:
# Challenge: Change cell at (2,0) to 0.37
# This will change the data frame permanently
df.iloc[2, 0] = .37
df

0         1         2
0  0.849933       NaN       NaN
1  0.096458       NaN       NaN
2  0.370000       NaN -0.970226
3  0.411543       NaN -0.374906
4  0.144656  1.082482  0.975774
5 -0.759141  0.701347 -0.538854
6 -0.496170 -0.490029 -1.265389

In [ ]:
# Display df output
df

0         1         2
0 -0.204708       NaN       NaN
1 -0.555730       NaN       NaN
2  0.370000       NaN  0.769023
3  1.246435       NaN -1.296221
4  0.274992  0.228913  1.352917
5  0.886429 -2.001637 -0.371843
6  1.669025 -0.438570 -0.539741

In [14]:
# Challenge
# Another dummy data 2
np.random.seed(1234)
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.636524  0.015696
3 -2.242685  1.150036  0.991946
4  0.953324 -2.021255 -0.334077
5  0.002118  0.405453  0.289092

In [16]:
# iloc - integer index
df.iloc[2: , 1] = np.nan
df.iloc[4: , 2] = np.nan
df

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588       NaN  0.015696
3 -2.242685       NaN  0.991946
4  0.953324       NaN       NaN
5  0.002118       NaN       NaN

In [17]:
# Fill na forward
df.fillna(method = "ffill")

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685 -0.720589  0.991946
4  0.953324 -0.720589  0.991946
5  0.002118 -0.720589  0.991946

In [18]:
# fill na limit to 2
df.fillna(method = "ffill", limit = 1)

0         1         2
0  0.471435 -1.190976  1.432707
1 -0.312652 -0.720589  0.887163
2  0.859588 -0.720589  0.015696
3 -2.242685       NaN  0.991946
4  0.953324       NaN  0.991946
5  0.002118       NaN       NaN

In [19]:
# Another example 3
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [22]:
# Data imputation using median
data.fillna(data.median())

0    1.0
1    3.5
2    3.5
3    3.5
4    7.0
dtype: float64

# **Data Transformation**
Filtering, cleaning, and other transformations

### **Removing Duplicates**

In [28]:
# Example data with duplicate rows
data = pd.DataFrame({"k1": ['one', 'two'] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4,]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

# The ***duplicated() function*** returns a ***Boolean Series*** indicating whether each row is a duplicate to those in an ***earlier row***

In [24]:
data.duplicated?

In [29]:
# Detect duplication of data row-wise
# data.duplicated?
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [30]:
# Returns a DataFrame with rows where the duplicated array is filtered out
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [32]:
range(7)

range(0, 7)

In [31]:
# Add dummy data
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [33]:
# Filter duplicates based only on the "k1" column
# By default, keep the first observed value combination
data.drop_duplicates(subset = ['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [36]:
# Passing keep="last" will return the last one
# Remove index 5
print(data)
print('\n--------------\n')
data.drop_duplicates(['k1', 'k2'], keep = 'last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

--------------



k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### **Transforming Data Using Mapping**

In [38]:
# Mock data
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'pastrami', 'corned beef', 'bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [43]:
# Mapping of each distinct animal type
# This is a library of food to animal
meat_to_animal = {
    "bacon": "pig",
    "pulled pork": "pig",
    "pastrami": "cow",
    "corned beef": "cow",
    "honey ham": "pig",
    "nova lox": "salmon"
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [44]:
# Mapping method
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### **Replacing Values**

In [46]:
# Mock data
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [50]:
# Set -999 values as sentinel value for missing data
# sentinel value -> unique value indicating certain meaning
# Special value that is used to signal the end of a sequence, indicate an error,
# or serve as a termination condition in a program.
data.replace(-999, "No data available")

0                  1.0
1    No data available
2                  2.0
3    No data available
4              -1000.0
5                  3.0
dtype: object

In [51]:
# Replace multiple sentinel values at once
data.replace([-999, -1000], "No data available")

0                  1.0
1    No data available
2                  2.0
3    No data available
4    No data available
5                  3.0
dtype: object

In [52]:
# Use a different replacement for each sentinel value
data.replace([-999, -1000], ["No data available", "No No No"])

0                  1.0
1    No data available
2                  2.0
3    No data available
4             No No No
5                  3.0
dtype: object

In [53]:
# Argument passed as a dictionary
data.replace({-999: "No data available", -1000: "No no no"})

0                  1.0
1    No data available
2                  2.0
3    No data available
4             No no no
5                  3.0
dtype: object

### **Renaming Axis Indexes**

In [55]:
# Mock example
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index = ['ohio', 'ukm', 'bangi'],
                    columns = ['one', 'two', 'tiga', 'empat'])
data

one  two  tiga  empat
ohio     0    1     2      3
ukm      4    5     6      7
bangi    8    9    10     11

In [56]:
# Add another column
data['five'] = np.random.standard_normal(3)
data

one  two  tiga  empat      five
ohio     0    1     2      3  1.321158
ukm      4    5     6      7 -1.546906
bangi    8    9    10     11 -0.202646

In [62]:
# Define a transform() function
def transform(x):
    return x[:].upper()

data.index.map(transform)

Index(['OHIO', 'UKM', 'BANGI'], dtype='object')

In [64]:
# Rename indexes
# To uppercase
data.index = data.index.map(transform)
data

one  two  tiga  empat      five
OHIO     0    1     2      3  1.321158
UKM      4    5     6      7 -1.546906
BANGI    8    9    10     11 -0.202646

# Create a transformed version of a dataset ***without modifying the original***, a useful method is ***rename***

In [65]:
# Display data
data

one  two  tiga  empat      five
OHIO     0    1     2      3  1.321158
UKM      4    5     6      7 -1.546906
BANGI    8    9    10     11 -0.202646

In [66]:
# rename() function
# columns -> column names
data.rename(index = str.title, columns = str.upper)

ONE  TWO  TIGA  EMPAT      FIVE
Ohio     0    1     2      3  1.321158
Ukm      4    5     6      7 -1.546906
Bangi    8    9    10     11 -0.202646

In [68]:
# Rename can be used in conjunction with a dictionary-like object
data.rename(index = {"OHIO": "New York", "New": "Old"},
            columns = {'tiga': 'peekaboo', 'five': 'Seven'})

one  two  peekaboo  empat     Seven
New York    0    1         2      3  1.321158
UKM         4    5         6      7 -1.546906
BANGI       8    9        10     11 -0.202646

In [69]:
# The original data remains intact
print(data)

       one  two  tiga  empat      five
OHIO     0    1     2      3  1.321158
UKM      4    5     6      7 -1.546906
BANGI    8    9    10     11 -0.202646


### **Discretization and Binning**

In [72]:
# Mock data
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [73]:
# Divide into bins of 18 to 25, 26 to 35, 36 to 60, and finally 61 and older
# returns a Categorical object
# "(" -> Open parenthesis: Indicates that the value is not included in the interval
# "]" -> Closed square bracket: Indicates that the value is included in the interval
# (18, 25] -> interval includes values greater than 18 and less than or equal to 25.
bins = [18, 25, 35, 100]
age_cat = pd.cut(ages, bins)
age_cat

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 100], (35, 100], (35, 100], (25, 35]]
Length: 12
Categories (3, interval[int64, right]): [(18, 25] < (25, 35] < (35, 100]]

### **Unique pandas categorical object**

In [74]:
# Codes
age_cat.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1], dtype=int8)

In [75]:
# Categories
age_cat.categories

IntervalIndex([(18, 25], (25, 35], (35, 100]], dtype='interval[int64, right]')

In [78]:
# Accessing single elements
# closed -> inclusive
age_cat.categories[2]

Interval(35, 100, closed='right')

In [79]:
# Count number of each category
pd.value_counts(age_cat)

(18, 25]     5
(35, 100]    4
(25, 35]     3
dtype: int64

• **parenthesis, ( )** means that the side is open (**exclusive**)

• **square . [ ]** bracket means it is closed [**inclusive**]

• Example: **[first1, last1)** , the range starts with first1 (and includes it), but ends just before last1

In [80]:
# Inclusive of left, exclusive (not include) right
pd.cut(ages, bins, right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [35, 100), [35, 100), [35, 100), [25, 35)]
Length: 12
Categories (3, interval[int64, left]): [[18, 25) < [25, 35) < [35, 100)]

In [81]:
# Exclusive of left, inclusive of right
pd.cut(ages, bins, right = True)

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 100], (35, 100], (35, 100], (25, 35]]
Length: 12
Categories (3, interval[int64, right]): [(18, 25] < (25, 35] < (35, 100]]

In [82]:
# Override the default interval-based bin labeling by passing a list or
# array to the labels option
gp_names = ["Youth", "MiddleAge", "Senior"]
pd.cut(ages, bins, labels=gp_names)

['Youth', 'Youth', 'Youth', 'MiddleAge', 'Youth', ..., 'MiddleAge', 'Senior', 'Senior', 'Senior', 'MiddleAge']
Length: 12
Categories (3, object): ['Youth' < 'MiddleAge' < 'Senior']

In [84]:
# Some mock data
data = np.random.uniform(size = 20)
data

array([0.65137814, 0.39720258, 0.78873014, 0.31683612, 0.56809865,
       0.86912739, 0.43617342, 0.80214764, 0.14376682, 0.70426097,
       0.70458131, 0.21879211, 0.92486763, 0.44214076, 0.90931596,
       0.05980922, 0.18428708, 0.04735528, 0.67488094, 0.59462478])

In [86]:
# Pass an integer number of bins to pandas.cut to compute equal-length bins
# Based on the minimum and maximum values in the data
# Compute equal-length bins
# four quadrants -> each is 25%
# Precision=2 option limits the decimal precision to two digits
pd.cut(data, 4, precision = 2)

[(0.49, 0.71], (0.27, 0.49], (0.71, 0.92], (0.27, 0.49], (0.49, 0.71], ..., (0.046, 0.27], (0.046, 0.27], (0.046, 0.27], (0.49, 0.71], (0.49, 0.71]]
Length: 20
Categories (4, interval[float64, right]): [(0.046, 0.27] < (0.27, 0.49] < (0.49, 0.71] <
                                           (0.71, 0.92]]

In [87]:
# Pandas.qcut bins the data based on sample quantiles
# Showed -3.2899999999999996 because it is not included or not inclusive
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision = 2)
quartiles

[(-3.2899999999999996, -0.63], (-0.63, 0.011], (0.011, 0.65], (-3.2899999999999996, -0.63], (0.65, 3.39], ..., (-0.63, 0.011], (0.011, 0.65], (0.65, 3.39], (0.011, 0.65], (-3.2899999999999996, -0.63]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.2899999999999996, -0.63] < (-0.63, 0.011] < (0.011, 0.65] <
                                           (0.65, 3.39]]

In [88]:
# Count each catagory
pd.value_counts(quartiles)

(-3.2899999999999996, -0.63]    250
(-0.63, 0.011]                  250
(0.011, 0.65]                   250
(0.65, 3.39]                    250
dtype: int64

In [89]:
# Another example
# Based on user-defined quartiles
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.278, -1.239]    100
(-1.239, 0.011]     400
(0.011, 1.194]      400
(1.194, 3.392]      100
dtype: int64

### **Detecting and Filtering Outliers**

In [90]:
# DataFrame with some normally distributed data
# DataFrame of 1000x4
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data

0         1         2         3
0   -0.383074  2.889170 -0.980746  0.006740
1   -0.434959 -0.391216 -1.669522  0.449691
2   -1.740152  0.580979 -0.604593 -0.390135
3   -1.535534 -0.906693 -0.164389  0.353838
4   -0.340616  0.842821 -0.458246  0.062401
..        ...       ...       ...       ...
995 -0.059937  1.787308 -0.938496  0.977138
996  0.274726  1.878362  2.112952 -0.551003
997  0.750379 -0.959051 -0.004301  1.934280
998  0.415440 -0.405548  0.566740  1.606353
999  0.339533 -1.041291 -0.263567 -0.119890

[1000 rows x 4 columns]

In [91]:
# Explore the dataset in terms of statistics
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.020744     0.045654     0.002458     0.061400
std       0.984292     0.993026     1.012160     1.034712
min      -3.981365    -2.848829    -3.598630    -3.429621
25%      -0.640929    -0.641745    -0.660299    -0.644033
50%      -0.011492     0.077115     0.015607     0.045742
75%       0.672608     0.704776     0.701750     0.751576
max       3.119602     2.923515     3.018729     3.693038

In [92]:
# Find values in one of the columns exceeding 3 in absolute value
# Extracting 3rd column
col = data[2]
col[col.abs() > 3]

158   -3.598630
466    3.018729
Name: 2, dtype: float64

In [93]:
# Select any rows having at least one value exceeding sd of 3 or –3
data[(data.abs() > 3).any(axis = "columns")]

0         1         2         3
15  -3.981365 -0.725083 -0.305984 -0.990465
41   0.000617 -1.309392 -1.232270 -3.429621
73  -0.046211  1.955855 -0.007595  3.128667
158 -0.231526  0.430063 -3.598630  1.460734
466  0.309719  0.050276  3.018729 -1.144715
639  0.919885  0.899716  1.105227  3.693038
718  0.221424 -1.201303  0.972384 -3.185259
781  0.688612 -0.051223 -0.069972 -3.144777
993  3.119602  0.595783  0.834366 -0.424451

In [94]:
# Cap values outside the interval, more than abs(sd) = 3 to minimum –3 and maximum 3
data[data.abs() > 3] = np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.021606     0.045654     0.003037     0.061338
std       0.980410     0.993026     1.010148     1.029758
min      -3.000000    -2.848829    -3.000000    -3.000000
25%      -0.640929    -0.641745    -0.660299    -0.644033
50%      -0.011492     0.077115     0.015607     0.045742
75%       0.672608     0.704776     0.701750     0.751576
max       3.000000     2.923515     3.000000     3.000000

### **Permutation and Random Sampling**
Permutation - randomly reordering

In [ ]:
# 2d array of 5x7


0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [ ]:
# Random sampling


array([4, 2, 3, 0, 1])

In [ ]:
# sampling of the array


0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [ ]:
# Another way


0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13

In [ ]:
# Select a permutation of the columns


array([2, 0, 5, 1, 4, 6, 3])

In [ ]:
# Sample the colummns
print(df)
print('\n--------\n')


    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

--------



2   0   5   1   4   6   3
0   2   0   5   1   4   6   3
1   9   7  12   8  11  13  10
2  16  14  19  15  18  20  17
3  23  21  26  22  25  27  24
4  30  28  33  29  32  34  31

In [ ]:
# Select a random subset without replacement


0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
2  14  15  16  17  18  19  20

In [ ]:
# Example dataset


0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [ ]:
# Generate a sample with replacement


3    6
0    5
1    7
2   -1
4    4
dtype: int64

### **Computing Indicator/Dummy Variables**
Converting a categorical variable into a dummy or indicator matrix

In [ ]:
# Example dataframe
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Get dummy dataFrame based on the key


a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [ ]:
# Add a prefix


key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [ ]:
# Example data from previous
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
# Merging of dataset based on the same index number
print(df)
print('\n--------\n')
print(dummies)
print('\n--------\n')


  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

--------

   key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

--------



data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [ ]:
# DataFrame with multiple categories
# movies.dat -> Data can be downlaoded here: https://bit.ly/3VA5elU


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller

In [ ]:
# Get data from the genres column


Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1

### **String Manipulation**

In [ ]:
# A comma-separated string can be broken into pieces with split


['a', 'b', '  guido']

In [ ]:
# Split is often combined with strip to trim whitespace


['a', 'b', 'guido']

In [ ]:
# Substrings could be concatenated together with a
# Two-colon delimiter using addition


'a::b::guido'

In [ ]:
# Another way


'a::b::guido'

In [ ]:
# Return starting index of the first occurrence of passed substring
# If found in the string


10

In [ ]:
# Count returns the number of occurrences


2

In [ ]:
# replace() -> substitute occurrences of one pattern for another


'a::b::  guido'

### **Regular Expressions**
***regex*** describes a ***pattern to locate*** in the text, which can then be used for many purposes

In [ ]:
# Regex describing one or more whitespace characters -> \s+
# raw string (r"\s+") is often preferred in regular expressions to enhance readability and avoid potential issues with escaping
import re
text = "foo bar\t baz \tqux"
print(text)
print('\n----\n')


foo bar	 baz 	qux

----



['foo', 'bar', 'baz', 'qux']

In [ ]:
# Compile the regex with re.compile, forming a reusable regex object
# r'\s+' refers to sequence of whitespace
# Avoid unwanted escaping with \ in a regular expression


['foo', 'bar', 'baz', 'qux']

In [ ]:
# A block of text example
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

# Display text
print(text)

# The pattern to search
# Match a typical email address pattern
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive


Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com


In [ ]:
# Extract the information based on the pattern


['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

### **String Functions in pandas**
Cleaning up a messy dataset for analysis often requires a lot of string manipulation

In [ ]:
# A column containing strings with missing data
# in dictionary form
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
# Check missing data


Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
# Series has array-oriented methods for string operations that skip over
# and propagate NA values


Dave      True
Steve    False
Rob      False
Wes        NaN
dtype: object

In [ ]:
# String data type


Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [ ]:
# Boolean data type


Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

### **Categorical Data**

In [ ]:
# A mock data


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [ ]:
# Extract distinct values


array(['apple', 'orange'], dtype=object)

In [ ]:
# Count


apple     6
orange    2
dtype: int64

### **Categorical Extension Type in pandas**
integer-based categorical representation or ***encoding***

In [ ]:
# Some example Series
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

NameError: ignored

In [ ]:
# Convert df['fruit'] into categorical; original is a string


0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [ ]:
# Accessing the array attribute


pandas.core.arrays.categorical.Categorical

In [ ]:
# Category


Index(['apple', 'orange'], dtype='object')

In [ ]:
# codes


array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [ ]:
# Mapping between codes and categories
# enumerate() -> is used to iterate over the elements of c.categories along with their index positions
# Returns pairs of index and value.


{0: 'apple', 1: 'orange'}

### **Computations with Categoricals**

In [ ]:
# Some mock data
rng = np.random.default_rng(seed=12345)


array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [ ]:
# Compute a quartile binning and extract some statistics


[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [ ]:
# Using labels argument


['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [ ]:
# Accessing codes


array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [ ]:
# Use groupby to extract summary statistics


quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

### **Categorical Methods**

In [ ]:
# Some mock data


0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [ ]:
# cat provides access to categorical methods -> the codes
# returns the integer codes associated with each category in the categorical series


0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [ ]:
# Accessing the categories data


Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
# set_categories method to change new category


0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [ ]:
# value_counts for cat_s


a    2
b    2
c    2
d    2
dtype: int64

In [ ]:
# value_counts for cat_s2


a    2
b    2
c    2
d    2
e    0
dtype: int64

### **Hierarchical Indexing**

In [ ]:
# An example
data = pd.Series(np.random.uniform(size=9),
                 index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1,2,3,1,3,1,2,2,3]])
data

a  1    0.309067
   2    0.792981
   3    0.512137
b  1    0.015982
   3    0.079923
c  1    0.550706
   2    0.074008
d  2    0.931472
   3    0.701850
dtype: float64

In [ ]:
# Access the index


MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
# Partial indexing


1    0.015982
3    0.079923
dtype: float64

In [ ]:
# Partial indexing


b  1    0.015982
   3    0.079923
c  1    0.550706
   2    0.074008
dtype: float64

In [ ]:
# Partial indexing
# loc[] -> label-based indexing


b  1    0.015982
   3    0.079923
d  2    0.931472
   3    0.701850
dtype: float64

In [ ]:
# Partial indexing
print(data)
print('\n---------\n')


a  1    0.309067
   2    0.792981
   3    0.512137
b  1    0.015982
   3    0.079923
c  1    0.550706
   2    0.074008
d  2    0.931472
   3    0.701850
dtype: float64

---------



a    0.792981
c    0.074008
d    0.931472
dtype: float64

In [ ]:
# Rearrange this data into a DataFrame using its unstack method


1         2         3
a  0.309067  0.792981  0.512137
b  0.015982       NaN  0.079923
c  0.550706  0.074008       NaN
d       NaN  0.931472  0.701850

In [ ]:
# Reverse the operation of unstack -> stack


a  1    0.309067
   2    0.792981
   3    0.512137
b  1    0.015982
   3    0.079923
c  1    0.550706
   2    0.074008
d  2    0.931472
   3    0.701850
dtype: float64

In [ ]:
# Another example
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                     columns=[["Ohio", "Ohio", "Colorado"],
                              ["Green", "Red", "Green"]])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
# add key names


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [ ]:
# Partial indexing


color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### **Reordering and Sorting Levels**

In [ ]:
# Rearrange key


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [ ]:
# Another example of rearrange
# level=1 -> the sorting is based on the values in the second level of the index.
print(frame)
print('\n-------\n')


NameError: ignored

### **Summary Statistics by Level**

In [ ]:
# Sum


state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [ ]:
# Another example


color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

### **Indexing with a DataFrame’s columns**

In [ ]:
# Example dataframe
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                      "c": ["one", "one", "one", "two", "two",
                            "two", "two"],
                      "d":[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [ ]:
# Create a new DataFrame using one or more of its columns as the index


a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [ ]:
# Leave the column intact


a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [ ]:
# Move the index back to columns


c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

### **Combining and Merging Datasets**

### **Database-Style DataFrame Joins**

In [ ]:
# Example datasets
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [ ]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [ ]:
# By default - inner join
# keeps only the rows where the "key" values exist in both DataFrames
# Using the same common "feature"


key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
# Different column names
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})

In [ ]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [ ]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [ ]:
# Merge - inner join by default - intersection
# Using specific key


rkey  data2 lkey  data1
0    a      0    a      2
1    a      0    a      4
2    a      0    a      5
3    b      1    b      0
4    b      1    b      1
5    b      1    b      6

In [ ]:
# Merge - outer join - union
print(df1)
print('\n----\n')
print(df2)
print('\n----\n')


  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

----

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

----



key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    b      5      1
5    b      5      3
6    a      2      0
7    a      2      2
8    a      4      0
9    a      4      2
10   c      3   <NA>
11   d   <NA>      4

In [ ]:
# Merge - outer join - union
print(df3)
print('\n----\n')
print(df4)
print('\n----\n')


  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

----

  rkey  data2
0    a      0
1    b      1
2    d      2

----



lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

### **Many-to-many merges**

In [ ]:
# A mock data
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})

In [ ]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [ ]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [ ]:
# left-join


key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [ ]:
# inner join
# Intersection


key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   b      5      1
5   b      5      3
6   a      2      0
7   a      2      2
8   a      4      0
9   a      4      2

In [ ]:
# merge with multiple keys
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})


In [ ]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [ ]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [ ]:
# Outer join
pd.merge(left, right, on=["key1", "key2"], how="outer")

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  foo  two     2  <NA>
3  bar  one     3     6
4  bar  two  <NA>     7

### **Concatenating Along an Axis**
***axis=0***; ***moves down*** the column

***axis=1***; ***moves across*** the column to the right

In [ ]:
# an example



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Along the column


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

### **Reshaping**
reshaperearranging tabular data

### ***Reshaping with Hierarchical Indexing***

In [ ]:
# Example data
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                                     name="number"))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Using the stack method to pivot the columns into the rows


state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [ ]:
# Rearrange


number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
# Unstack a different level by passing a level number or name


state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
# Using name


state   Ohio  Colorado
number                
one        0         3
two        1         4
three      2         5

In [ ]:
# Example


a    0
b    1
c    2
d    3
dtype: Int64

In [ ]:
# example 2


c    4
d    5
e    6
dtype: Int64

In [ ]:
# Concatenate


one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [ ]:
# Unstacking


a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [ ]:
# Return original state


one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

# **All the best and good luck!!!**









